site_name: NoctVM Game Engine Docs
repo_url: https://github.com/awemorris/NoctVM.git
use_directory_urls: false

nav:
  - Home: index.md
  - Getting Started: gettingstarted.md

theme:
  name: material
  features:
    - navigation.expand
    - navigation.tabs
    - search.suggest
    - content.code.annotate
